### ISSUE TITLE
Import error with Libmagic

### ISSUE THREAD

**Issue by aniforverizon** [rozuur/s3browser#12]
Can you please help me out with this :

![image](https://user-images.githubusercontent.com/43361858/115195400-556fc580-a10c-11eb-8794-fa27d14467fa.png)

![image](https://user-images.githubusercontent.com/43361858/115195475-6e787680-a10c-11eb-8c1b-80c0860337eb.png)

ubuntu@ip-172-31-1-72:~/s3browser$ docker run -t -i --env-file ~/aws.env -p9000:9000 s3browser ./s3browser/start_gunicorn.sh
[2021-04-19 07:09:07 +0000] [9] [INFO] Starting gunicorn 19.9.0
[2021-04-19 07:09:07 +0000] [9] [INFO] Listening at: http://0.0.0.0:9000 (9)
[2021-04-19 07:09:07 +0000] [9] [INFO] Using worker: gthread
[2021-04-19 07:09:07 +0000] [12] [INFO] Booting worker with pid: 12
[2021-04-19 07:09:07 +0000] [13] [INFO] Booting worker with pid: 13
[2021-04-19 07:09:08 +0000] [12] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/s3browser/wsgi.py", line 1, in <module>
    from app import app
  File "/s3browser/app/__init__.py", line 5, in <module>
    from app import routes
  File "/s3browser/app/routes.py", line 4, in <module>
    import magic
  File "/opt/venv/lib/python3.7/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
[2021-04-19 07:09:08 +0000] [12] [INFO] Worker exiting (pid: 12)
[2021-04-19 07:09:08 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/s3browser/wsgi.py", line 1, in <module>
    from app import app
  File "/s3browser/app/__init__.py", line 5, in <module>
    from app import routes
  File "/s3browser/app/routes.py", line 4, in <module>
    import magic
  File "/opt/venv/lib/python3.7/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
[2021-04-19 07:09:08 +0000] [13] [INFO] Worker exiting (pid: 13)
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 210, in run
    self.sleep()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 360, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/opt/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by rozuur** [comment]
Thanks for reporting this issue. I have fixed the issue, please verify.
